vert.x版本升级到4.3.8 vertx-web Verx-Web   Fix the webroot escape to classpath on windows (CVE-2023-24815)   修复窗口上网页根转义到类路径的问题 （ CVE-2023-24815 ）
  Fix CORS cache behavior with allow credentials
  使用允许凭据修复 CORS 缓存行为

  NullPointerException in private Constructor of OAuth2AuthHandlerImpl
  OAuth2AuthHandlerImpl 私有构造函数中的 NullPointerException

vertx-hazelcast Verx-Hazelcast
  Upgrade to Hazelcast 4.2.7
  升级到 Hazelcast 4.2.7

  Failed to handle memberRemoved: NullPointerException
  无法处理成员已删除：空指针异常

vert.x
  SSL threading improvements 4.3
  SSL 线程改进 4.3

  TCP server regression now accepts to bind to a port greater than 65535
and fail to report the failure.
  TCP 服务器回归现在接受绑定到大于 65535 的端口，但无法报告故障。

  Blocked thread checker named worker threads leak
  名为工作线程泄漏的被阻止线程检查器

  Memory leak inside BlockedThreadChecker (OutOfMemoryError)
  BlockedThreadChecker 內部的記憶體漏漏 （OutOfMemoryError）

  JsonParser should process fully the possible events when processing
malformed input
  JsonParser 在处理格式错误的输入时应完全处理可能的事件

  java.lang.IllegalArgumentException: port out of range
  java.lang.IllegalArgumentException： port Out of range

  SSL blocking operations can now be executed on the vertx internal
worker pool
  现在可以在 vertx 内部工作线程池上执行 SSL 阻止操作

  Connection pool post task stack overflow fix
  连接池后任务堆栈溢出修复

  Connection pool post task stack overflow
  连接池后任务堆栈溢出

  Regression in Kotlin Compatibility of SLF4JLogDelegate from 4.3.4
  来自 4.3.4 的 SLF4JLogDelegate 的 Kotlin 兼容性回归

  nonProxyHost property ignored in Copy Constructor of ClientOptionsBase
  在客户端选项库的复制构造函数中忽略的非代理主机属性

  Invalid header name [X-B3-TraceId] when WebClient requests with HTTP2
and OpenTelemetry B3Propagator tracing options
  当 WebClient 使用 HTTP2 和开放遥测 B3传播器跟踪选项请求时标头名称 [X-B3-TraceId] 无效

  Inconsistent error handling with JsonParser
  与 JsonParser 的错误处理不一致